[package]
name = "plugin" # 名称固定为plugin，请勿更改
version = "1.0.0"
authors = ["pot-app"]
edition = "2021"

[lib]
crate-type = ["dylib"] # pot只支持dylib类型动态库，请勿修改

[dependencies]
dirs = "5.0.1"
num_cpus = "1.16.0"
serde_json = "1.0"
