name: 'Build for Linux'
branding:
  icon: user-check
  color: gray-dark
inputs:
  target:
    required: true
    description: 'Rust Target'
  toolchain:
    required: true
    description: 'Rust Toolchain'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
    - ${{ inputs.toolchain }}